# Generated by Django 2.1.5 on 2019-08-10 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Huawei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fm_radio', models.BooleanField()),
                ('ir_port', models.BooleanField()),
                ('model', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fm_radio', models.BooleanField()),
                ('ir_port', models.BooleanField()),
                ('model', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('os_sys', models.TextField()),
                ('resolution', models.TextField()),
                ('cam_matrix', models.TextField()),
                ('ram_memory', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='lg',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phones.Phone'),
        ),
        migrations.AddField(
            model_name='huawei',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phones.Phone'),
        ),
    ]
